### PR TITLE
Move telegram to http.client

### PR DESCRIPTION
**Pull request by alexjj**
I found the `curl -s` command didn't work, and I was going to change it to a `curl -X POST ` one but then figured why not use http.client like the pushover client.

Also added a python gitignore (from [Github](https://github.com/github/gitignore/blob/main/Python.gitignore))

### CODE REVIEW

**Comment by alexjj** [comment]
GM5ALX btw 😄

**Comment by n8acl** [comment]
I like this better. It is much cleaner. I was never really sold on using cURL but it was the easiest thing to use at the time when I could not find a decent Python library for telegram. I should have gone back and done something more elegant, but I don't use Telegram anymore so I never had a reason to. Thanks for this.

**Comment by n8acl** [comment]
Oh and for me, a gitignore is not needed. which is why I never included one. I have a repo setup separate from my dev/production environments that I copy the final files into to push, so extra files that should not be committed would not be. I know that for some people it would be an issue, but I make sure to separate my environments so that it is not an issue. So I removed that. However, thanks for the thought.

**Comment by alexjj** [comment]
Sure no worries. I use VS Code and it was zero effort to add it out of habit. Thanks for sharing the script and instructions!

**Comment by n8acl** [comment]
No problem. I use VSC as well.. I love it. Glad you have found some use for it. It was something simple I threw together for myself so I figured it could be something useful for someone else.

**Pull request merged**
